[package]
name = "vu"
version = "0.1.2"
edition = "2021"

[dependencies]
fast_image_resize = "4.2.1"
image = "0.25.2"
pico-args = "0.5.0"
pixels = "0.13.0"
winit = { version = "0.29", features = ["wayland", "rwh_05"], default-features = false }

[profile.release]
lto = "fat"
panic = "abort"
codegen-units = 1
